// frontend/v3-blog/src/views/PhotoGridView.vue
<template>
  <div class="photo">
    <nav class="photo__nav">
      <span>all</span>
      <span>beauty</span>
      <span>animal</span>
      <span>build</span>
      <span>landscape</span>
    </nav>
    <div class="photo__container">
      <img
        class="img"
        src="https://cdn.midjourney.com/2b2fc2b3-a75d-472c-8db5-efaa051ed83e/0_0.webp"
        alt=""
      />
      <img
        class="img"
        src="https://cdn.midjourney.com/2b2fc2b3-a75d-472c-8db5-efaa051ed83e/0_0.webp"
        alt=""
      />
      <img
        class="img"
        src="https://cdn.midjourney.com/e868b837-8367-44a3-9ead-fe3b8dc9fd61/0_0.webp"
        alt=""
      />
      <img
        class="img"
        src="https://cdn.midjourney.com/2b2fc2b3-a75d-472c-8db5-efaa051ed83e/0_0.webp"
        alt=""
      />

      <img
        class="img"
        src="https://cdn.midjourney.com/2b2fc2b3-a75d-472c-8db5-efaa051ed83e/0_0.webp"
        alt=""
      />
      <img
        class="img"
        src="https://cdn.midjourney.com/2b2fc2b3-a75d-472c-8db5-efaa051ed83e/0_0.webp"
        alt=""
      />
      <img
        class="img"
        src="https://cdn.midjourney.com/e868b837-8367-44a3-9ead-fe3b8dc9fd61/0_0.webp"
        alt=""
      />
      <img
        class="img"
        src="https://cdn.midjourney.com/2b2fc2b3-a75d-472c-8db5-efaa051ed83e/0_0.webp"
        alt=""
      />
      <img
        class="img"
        src="https://cdn.midjourney.com/2b2fc2b3-a75d-472c-8db5-efaa051ed83e/0_0.webp"
        alt=""
      />
      <img
        class="img"
        src="https://cdn.midjourney.com/2b2fc2b3-a75d-472c-8db5-efaa051ed83e/0_0.webp"
        alt=""
      />
      <img
        class="img"
        src="https://cdn.midjourney.com/e868b837-8367-44a3-9ead-fe3b8dc9fd61/0_0.webp"
        alt=""
      />
      <img
        class="img"
        src="https://cdn.midjourney.com/2b2fc2b3-a75d-472c-8db5-efaa051ed83e/0_0.webp"
        alt=""
      />
      <img
        class="img"
        src="https://cdn.midjourney.com/2b2fc2b3-a75d-472c-8db5-efaa051ed83e/0_0.webp"
        alt=""
      />
      <img
        class="img"
        src="https://cdn.midjourney.com/2b2fc2b3-a75d-472c-8db5-efaa051ed83e/0_0.webp"
        alt=""
      />
      <img
        class="img"
        src="https://cdn.midjourney.com/e868b837-8367-44a3-9ead-fe3b8dc9fd61/0_0.webp"
        alt=""
      />
      <img
        class="img"
        src="https://cdn.midjourney.com/2b2fc2b3-a75d-472c-8db5-efaa051ed83e/0_0.webp"
        alt=""
      />
      <img
        class="img"
        src="https://cdn.midjourney.com/2b2fc2b3-a75d-472c-8db5-efaa051ed83e/0_0.webp"
        alt=""
      />
      <img
        class="img"
        src="https://cdn.midjourney.com/2b2fc2b3-a75d-472c-8db5-efaa051ed83e/0_0.webp"
        alt=""
      />
      <img
        class="img"
        src="https://cdn.midjourney.com/e868b837-8367-44a3-9ead-fe3b8dc9fd61/0_0.webp"
        alt=""
      />
      <img
        class="img"
        src="https://cdn.midjourney.com/2b2fc2b3-a75d-472c-8db5-efaa051ed83e/0_0.webp"
        alt=""
      />
      <img
        class="img"
        src="https://cdn.midjourney.com/2b2fc2b3-a75d-472c-8db5-efaa051ed83e/0_0.webp"
        alt=""
      />
      <img
        class="img"
        src="https://cdn.midjourney.com/2b2fc2b3-a75d-472c-8db5-efaa051ed83e/0_0.webp"
        alt=""
      />
      <img
        class="img"
        src="https://cdn.midjourney.com/e868b837-8367-44a3-9ead-fe3b8dc9fd61/0_0.webp"
        alt=""
      />
      <img
        class="img"
        src="https://cdn.midjourney.com/2b2fc2b3-a75d-472c-8db5-efaa051ed83e/0_0.webp"
        alt=""
      />
      <img
        class="img"
        src="https://cdn.midjourney.com/2b2fc2b3-a75d-472c-8db5-efaa051ed83e/0_0.webp"
        alt=""
      />
      <img
        class="img"
        src="https://cdn.midjourney.com/2b2fc2b3-a75d-472c-8db5-efaa051ed83e/0_0.webp"
        alt=""
      />
      <img
        class="img"
        src="https://cdn.midjourney.com/e868b837-8367-44a3-9ead-fe3b8dc9fd61/0_0.webp"
        alt=""
      />
      <img
        class="img"
        src="https://cdn.midjourney.com/2b2fc2b3-a75d-472c-8db5-efaa051ed83e/0_0.webp"
        alt=""
      />
      <img
        class="img"
        src="https://cdn.midjourney.com/2b2fc2b3-a75d-472c-8db5-efaa051ed83e/0_0.webp"
        alt=""
      />
      <img
        class="img"
        src="https://cdn.midjourney.com/2b2fc2b3-a75d-472c-8db5-efaa051ed83e/0_0.webp"
        alt=""
      />
      <img
        class="img"
        src="https://cdn.midjourney.com/e868b837-8367-44a3-9ead-fe3b8dc9fd61/0_0.webp"
        alt=""
      />
      <img
        class="img"
        src="https://cdn.midjourney.com/2b2fc2b3-a75d-472c-8db5-efaa051ed83e/0_0.webp"
        alt=""
      />
    </div>
  </div>
</template>

<!-- 注意 这套写法有特别优秀的响应式效果 -->
<style lang="scss" scoped>
.photo {
  min-height: 100vh;

  &__nav {
    width: 120px;
    min-height: 100vh;
    padding-top: 60px;
    padding-left: 12px;
    padding-right: 12px;
    border-right: 1px solid #dbdbdb;
  }

  &__container {
    display: grid;
    grid-template-columns: repeat(auto-fit, minmax(200px, 1fr)); // 优质代码
    grid-gap: 12px;
    padding-left: 120px;
  }

  .img {
    max-width: 100%;
    margin: 6px;
  }
}

nav {
  span {
    text-align: left;
  }
}
</style>

// frontend/wei-front/src/app/pages/image/shared/components/photo-grid-view/photo-grid-view.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'wei-front-photo-grid-view',
  templateUrl: './photo-grid-view.component.html',
  styleUrls: ['./photo-grid-view.component.scss'],
  standalone: true,
})
export class PhotoGridViewComponent {}

<div class="photo">
    <!--
    <nav class="photo__nav">
        <span>all</span>
        <span>beauty</span>
        <span>animal</span>
        <span>build</span>
        <span>landscape</span>
    </nav>
    -->
    <div class="photo__container">
        <div class="photo__container__column">
            <img
                class="img"
                src="https://cdn.midjourney.com/2b2fc2b3-a75d-472c-8db5-efaa051ed83e/0_0.webp"
                alt=""
            />
            <img
                class="img"
                src="https://cdn.midjourney.com/2b2fc2b3-a75d-472c-8db5-efaa051ed83e/0_0.webp"
                alt=""
            />
            <img
                class="img"
                src="https://cdn.midjourney.com/e868b837-8367-44a3-9ead-fe3b8dc9fd61/0_0.webp"
                alt=""
            />
            <img
                class="img"
                src="https://cdn.midjourney.com/2b2fc2b3-a75d-472c-8db5-efaa051ed83e/0_0.webp"
                alt=""
            />
            <img
                class="img"
                src="https://cdn.midjourney.com/2b2fc2b3-a75d-472c-8db5-efaa051ed83e/0_0.webp"
                alt=""
            />
            <img
                class="img"
                src="https://cdn.midjourney.com/2b2fc2b3-a75d-472c-8db5-efaa051ed83e/0_0.webp"
                alt=""
            />
            <img
                class="img"
                src="https://cdn.midjourney.com/e868b837-8367-44a3-9ead-fe3b8dc9fd61/0_0.webp"
                alt=""
            />
            <img
                class="img"
                src="https://cdn.midjourney.com/2b2fc2b3-a75d-472c-8db5-efaa051ed83e/0_0.webp"
                alt=""
            />
            <img
                class="img"
                src="https://cdn.midjourney.com/2b2fc2b3-a75d-472c-8db5-efaa051ed83e/0_0.webp"
                alt=""
            />
            <img
                class="img"
                src="https://cdn.midjourney.com/2b2fc2b3-a75d-472c-8db5-efaa051ed83e/0_0.webp"
                alt=""
            />
            <img
                class="img"
                src="https://cdn.midjourney.com/e868b837-8367-44a3-9ead-fe3b8dc9fd61/0_0.webp"
                alt=""
            />
            <img
                class="img"
                src="https://cdn.midjourney.com/2b2fc2b3-a75d-472c-8db5-efaa051ed83e/0_0.webp"
                alt=""
            />
            <img
                class="img"
                src="https://cdn.midjourney.com/2b2fc2b3-a75d-472c-8db5-efaa051ed83e/0_0.webp"
                alt=""
            />
            <img
                class="img"
                src="https://cdn.midjourney.com/2b2fc2b3-a75d-472c-8db5-efaa051ed83e/0_0.webp"
                alt=""
            />
            <img
                class="img"
                src="https://cdn.midjourney.com/e868b837-8367-44a3-9ead-fe3b8dc9fd61/0_0.webp"
                alt=""
            />
            <img
                class="img"
                src="https://cdn.midjourney.com/2b2fc2b3-a75d-472c-8db5-efaa051ed83e/0_0.webp"
                alt=""
            />
            <img
                class="img"
                src="https://cdn.midjourney.com/2b2fc2b3-a75d-472c-8db5-efaa051ed83e/0_0.webp"
                alt=""
            />
        </div>
        <div class="photo__container__column">
            <img
                class="img"
                src="https://cdn.midjourney.com/2b2fc2b3-a75d-472c-8db5-efaa051ed83e/0_0.webp"
                alt=""
            />
            <img
                class="img"
                src="https://cdn.midjourney.com/2b2fc2b3-a75d-472c-8db5-efaa051ed83e/0_0.webp"
                alt=""
            />
            <img
                class="img"
                src="https://cdn.midjourney.com/e868b837-8367-44a3-9ead-fe3b8dc9fd61/0_0.webp"
                alt=""
            />
            <img
                class="img"
                src="https://cdn.midjourney.com/2b2fc2b3-a75d-472c-8db5-efaa051ed83e/0_0.webp"
                alt=""
            />
            <img
                class="img"
                src="https://cdn.midjourney.com/2b2fc2b3-a75d-472c-8db5-efaa051ed83e/0_0.webp"
                alt=""
            />
            <img
                class="img"
                src="https://cdn.midjourney.com/2b2fc2b3-a75d-472c-8db5-efaa051ed83e/0_0.webp"
                alt=""
            />
            <img
                class="img"
                src="https://cdn.midjourney.com/e868b837-8367-44a3-9ead-fe3b8dc9fd61/0_0.webp"
                alt=""
            />
            <img
                class="img"
                src="https://cdn.midjourney.com/2b2fc2b3-a75d-472c-8db5-efaa051ed83e/0_0.webp"
                alt=""
            />
            <img
                class="img"
                src="https://cdn.midjourney.com/2b2fc2b3-a75d-472c-8db5-efaa051ed83e/0_0.webp"
                alt=""
            />
            <img
                class="img"
                src="https://cdn.midjourney.com/2b2fc2b3-a75d-472c-8db5-efaa051ed83e/0_0.webp"
                alt=""
            />
            <img
                class="img"
                src="https://cdn.midjourney.com/e868b837-8367-44a3-9ead-fe3b8dc9fd61/0_0.webp"
                alt=""
            />
            <img
                class="img"
                src="https://cdn.midjourney.com/2b2fc2b3-a75d-472c-8db5-efaa051ed83e/0_0.webp"
                alt=""
            />
            <img
                class="img"
                src="https://cdn.midjourney.com/2b2fc2b3-a75d-472c-8db5-efaa051ed83e/0_0.webp"
                alt=""
            />
            <img
                class="img"
                src="https://cdn.midjourney.com/2b2fc2b3-a75d-472c-8db5-efaa051ed83e/0_0.webp"
                alt=""
            />
            <img
                class="img"
                src="https://cdn.midjourney.com/e868b837-8367-44a3-9ead-fe3b8dc9fd61/0_0.webp"
                alt=""
            />
            <img
                class="img"
                src="https://cdn.midjourney.com/2b2fc2b3-a75d-472c-8db5-efaa051ed83e/0_0.webp"
                alt=""
            />
        </div>
        <div class="photo__container__column">
            <img
                class="img"
                src="https://cdn.midjourney.com/2b2fc2b3-a75d-472c-8db5-efaa051ed83e/0_0.webp"
                alt=""
            />
            <img
                class="img"
                src="https://cdn.midjourney.com/2b2fc2b3-a75d-472c-8db5-efaa051ed83e/0_0.webp"
                alt=""
            />
            <img
                class="img"
                src="https://cdn.midjourney.com/e868b837-8367-44a3-9ead-fe3b8dc9fd61/0_0.webp"
                alt=""
            />
            <img
                class="img"
                src="https://cdn.midjourney.com/2b2fc2b3-a75d-472c-8db5-efaa051ed83e/0_0.webp"
                alt=""
            />
            <img
                class="img"
                src="https://cdn.midjourney.com/2b2fc2b3-a75d-472c-8db5-efaa051ed83e/0_0.webp"
                alt=""
            />
            <img
                class="img"
                src="https://cdn.midjourney.com/2b2fc2b3-a75d-472c-8db5-efaa051ed83e/0_0.webp"
                alt=""
            />
            <img
                class="img"
                src="https://cdn.midjourney.com/e868b837-8367-44a3-9ead-fe3b8dc9fd61/0_0.webp"
                alt=""
            />
            <img
                class="img"
                src="https://cdn.midjourney.com/2b2fc2b3-a75d-472c-8db5-efaa051ed83e/0_0.webp"
                alt=""
            />
            <img
                class="img"
                src="https://cdn.midjourney.com/2b2fc2b3-a75d-472c-8db5-efaa051ed83e/0_0.webp"
                alt=""
            />
            <img
                class="img"
                src="https://cdn.midjourney.com/2b2fc2b3-a75d-472c-8db5-efaa051ed83e/0_0.webp"
                alt=""
            />
            <img
                class="img"
                src="https://cdn.midjourney.com/e868b837-8367-44a3-9ead-fe3b8dc9fd61/0_0.webp"
                alt=""
            />
            <img
                class="img"
                src="https://cdn.midjourney.com/2b2fc2b3-a75d-472c-8db5-efaa051ed83e/0_0.webp"
                alt=""
            />
            <img
                class="img"
                src="https://cdn.midjourney.com/2b2fc2b3-a75d-472c-8db5-efaa051ed83e/0_0.webp"
                alt=""
            />
            <img
                class="img"
                src="https://cdn.midjourney.com/2b2fc2b3-a75d-472c-8db5-efaa051ed83e/0_0.webp"
                alt=""
            />
            <img
                class="img"
                src="https://cdn.midjourney.com/e868b837-8367-44a3-9ead-fe3b8dc9fd61/0_0.webp"
                alt=""
            />
            <img
                class="img"
                src="https://cdn.midjourney.com/2b2fc2b3-a75d-472c-8db5-efaa051ed83e/0_0.webp"
                alt=""
            />
        </div>
    </div>
</div>
